name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 1 * *' # Runs at midnight on the first day of every month

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push v2
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:amazon-linux-2"
          push: true
          tags: supergibbs/aws-cli-container:2
      -
        name: Build and push v2023
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:amazon-linux-2023"
          push: true
          tags: supergibbs/aws-cli-container:2023,supergibbs/aws-cli-container:latest
